### ISSUE TITLE
[web] Zustand store / zustand persisted store

### ISSUE THREAD

**Issue by skbrown333** [CookbookGG/web#1]
```
{
   cookbook,
   cookbooks,
   guides,
   swipeState,
   user,
   userAuthToken (persisted)
}
```

**Comment by skbrown333** [comment]
I think all services calls should happen in the store updaters

**Comment by FluentCoding** [comment]
im certain that putting service calls inside the store updaters would be a bad design choice, i think we can look into it when we're at that point
